version: "3.9"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: bss-saathi-frontend:latest
    container_name: bss-saathi-frontend
    ports:
      - "8080:80"
    restart: unless-stopped

